server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/patient/**,/api/auth/**

        - id: provider-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/providers/**

        - id: medical-record-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/records/**
